Repository harmony-one/harmony, pull requests merged in 2019-02, with the labels that each got.

#389 Add Faucet Contract to contracts
  contracts/Faucet.sol
  test/chain/main.go
Labels: easy-to-review

#392 Add multicast interface and first implementation
  p2p/group.go
  p2p/group_test.go
  p2p/host.go
  p2p/host/hostv1/hostv1.go
  p2p/host/hostv2/hostv2.go
  p2p/host/hostv2/hostv2_test.go
  p2p/host/hostv2/mock/hostv2_mock.go
  p2p/host/mock/host_mock.go
  p2p/p2pimpl/p2pimpl.go
  scripts/list_harmony_go_files.sh
Labels: PLEASE REVIEW, enhancement

#394 Enable libp2p peer discovery and test
  cmd/harmony.go
  scripts/go_executable_build.sh
  test/deploy.sh
Labels: enhancement

#399 add error variables for p2p/host
  p2p/errors.go
  p2p/host/hostv2/hostv2.go
  p2p/host/message.go
  p2p/host/message_test.go
Labels: easy-to-review

#412 [FIX] integer divide by zero error
  node/node_handler.go
Labels: easy-to-review

#437 Update Binary and Staking Calls based on new staking contract
  node/contract.go
  node/node.go
  node/node_test.go
Labels: easy-to-review
