Repository harmony-one/harmony, pull requests merged in 2020-05, with the labels that each got.

#2921 Msg copy fix
  numeric/decimal.go
  numeric/decimal_test.go
  staking/types/commission.go
  staking/types/commission_test.go
  staking/types/messages.go
  staking/types/messages_test.go
Labels: PLEASE REVIEW, bug, core, low priority

#2924 Fix error sink msg duplication & false positives
  core/tx_pool.go
  core/tx_pool_test.go
  core/types/transaction.go
  core/types/tx_errorsink.go
  hmy/api_backend.go
  hmy/backend.go
  internal/configs/sharding/testnet.go
  internal/hmyapi/apiv1/backend.go
  internal/hmyapi/apiv1/transactionpool.go
  internal/hmyapi/apiv2/backend.go
  internal/hmyapi/apiv2/transactionpool.go
  internal/hmyapi/backend.go
  node/node.go
  node/rpc.go
  staking/types/transaction.go
  test/chain/main.go
Labels: bug

#2949 Add SenderAddress to plain Tx Type
  core/tx_pool.go
  core/tx_pool_test.go
  core/types/transaction.go
  core/types/tx_pool.go
  internal/hmyapi/apiv1/types.go
  internal/hmyapi/apiv2/types.go
Labels: enhancement

#3071 [network] Limit client sync connection
  api/service/syncing/syncing.go
  api/service/syncing/syncing_test.go
Labels: PLEASE REVIEW
