Repository harmony-one/harmony, pull requests merged in 2020-04, with the labels that each got.

#2793 [node] bingo with signature information
  node/node_handler.go
Labels: cosmetic

#2817 [node] Redundant field removed - dead files & scripts , update deprecated libp2p package names, fold p2p code
  .gitmodules
  api/service/discovery/discovery_test.go
  api/service/discovery/service.go
  api/service/networkinfo/service.go
  api/service/networkinfo/service_test.go
  cmd/bootnode/main.go
  cmd/harmony/main.go
  consensus/consensus_service.go
  consensus/consensus_service_test.go
  consensus/consensus_test.go
  consensus/consensus_v2.go
  consensus/construct_test.go
  consensus/leader.go
  consensus/threshold.go
  consensus/validator.go
  consensus/view_change.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  node/node.go
  node/node_cross_shard.go
  node/node_handler.go
  node/node_handler_test.go
  node/node_test.go
  p2p/backoff.go
  p2p/backoff_test.go
  p2p/errors.go
  p2p/host.go
  p2p/host/hostv2/hostv2.go
  p2p/host/message.go
  p2p/p2p.go
  p2p/p2pimpl/p2pimpl.go
  p2p/stream.go
  p2p/utils/flags.go
  p2p/utils/flags_test.go
  test/configs/archival-oneshard.txt
  test/configs/beaconchain10.txt
  test/configs/beaconchain20.txt
  test/configs/beaconchain40.txt
  test/configs/beaconchain5.txt
  test/configs/beaconchain6.txt
  test/configs/local.txt
  test/configs/newnode-oneshard.txt
  test/configs/pangaea.txt
  test/configs/ten-oneshard.txt
  test/configs/thirty-oneshard.txt
  test/consensus_testplan.md
  test/test_before_submit.sh
Labels: libp2p

#2877 Add viewID to block signed content
  api/proto/node/node.go
  consensus/leader.go
  consensus/signature/signature.go
  consensus/threshold.go
  consensus/validator.go
  consensus/view_change.go
  core/types/crosslink.go
  internal/chain/engine.go
  node/node_cross_link.go
  node/node_explorer.go
  staking/slash/double-sign.go
  staking/slash/double-sign_test.go
  staking/verify/verify.go
Labels: core, pangaea3
