Repository harmony-one/harmony, pull requests merged in 2021-06, with the labels that each got.

#3733 [rpc] Fix cache lead to inconsistent result
  rpc/blockchain.go
Labels: bug

#3727 [rpc] Add rate limit data to metrics
  cmd/harmony/flags_test.go
  internal/configs/node/network.go
  rpc/blockchain.go
  rpc/metrics.go
Labels: easy-to-review, enhancement

#3746 [SYNC] Add a hard cap to getBlocks request at server end
  node/node_syncing.go
Labels: WIP

#3762 [metrics] Add crosslink messages to metrics
  node/metrics.go
  node/node_cross_link.go
  node/node_syncing.go
Labels: enhancement

#3790 Explorer db schema
  api/service/explorer/interface.go
  api/service/explorer/interface_test.go
  api/service/explorer/migration.go
  api/service/explorer/migration_test.go
  api/service/explorer/schema.go
  api/service/explorer/schema_test.go
  api/service/explorer/service.go
  api/service/explorer/storage.go
  api/service/explorer/storage_test.go
  api/service/explorer/structs.go
  go.mod
  node/node_explorer.go
Labels: WIP

#3795 [p2p] Try to fix P2P memory issue
  go.mod
  p2p/types/peerAddr.go
Labels: WIP, bug
