Repository harmony-one/harmony, pull requests merged in 2023-10, with the labels that each got.

#4503 HIP-30 Shard Reduction Process
  Makefile
  cmd/harmony/default.go
  cmd/harmony/flags.go
  cmd/harmony/flags_test.go
  cmd/harmony/main.go
  consensus/consensus_service.go
  consensus/metrics.go
  core/blockchain.go
  core/blockchain_impl.go
  core/blockchain_stub.go
  core/epochchain.go
  core/genesis.go
  core/preimages.go
  core/rawdb/accessors_state.go
  core/rawdb/schema.go
  core/state_processor.go
  internal/chain/reward.go
  internal/cli/flag.go
  internal/cli/parse.go
  internal/configs/harmony/harmony.go
  internal/configs/node/config.go
  internal/configs/sharding/testnet.go
  internal/params/config.go
  internal/params/config_test.go
  internal/params/protocol_params.go
  internal/shardchain/shardchains.go
  node/node.go
  node/node_newblock.go
  node/worker/worker.go
  rpc/preimages.go
  rpc/rpc.go
  staking/reward/values.go
Labels: Next Release, HIP-30

#4523 use new(big.Int) so we don't modify the epoch value
  internal/params/config.go
Labels: ready-to-merge

#4526 enable hip30 epoch for testnet
  core/state_processor.go
  internal/params/config.go
Labels: ready-to-merge

#4529 fix preimage import bugs
  core/preimages.go
Labels: ready-to-merge

#4532 fix decryptRaw issue for nil/empty data
  internal/blsgen/lib.go
Labels: ready-to-merge

#4527 update deprecated ioutil
  accounts/abi/bind/auth.go
  accounts/keystore/account_cache_test.go
  accounts/keystore/file_cache.go
  accounts/keystore/key.go
  accounts/keystore/keystore_test.go
  accounts/keystore/passphrase.go
  accounts/keystore/passphrase_test.go
  accounts/keystore/plain_test.go
  cmd/harmony/config.go
  cmd/harmony/config_test.go
  cmd/harmony/main.go
  core/genesis_util.go
  core/tx_pool_test.go
  core/vm/instructions_test.go
  eth/rpc/gzip.go
  eth/rpc/http.go
  eth/rpc/method_filter.go
  eth/rpc/server_test.go
  hmy/tracer.go
  hmy/tracers/internal/tracers/assets.go
  internal/blsgen/kms.go
  internal/blsgen/kms_test.go
  internal/blsgen/lib.go
  internal/blsgen/passphrase.go
  internal/blsgen/passphrase_test.go
  internal/blsgen/utils_test.go
  internal/utils/passphrase.go
  internal/utils/testing/tempfile.go
  node/node.go
  staking/effective/calculate_test.go
  webhooks/yaml.go
Labels: ready-to-merge

#4520 Improvements for revert command.
  api/service/stagedsync/sync_config.go
  cmd/harmony/main.go
  core_test/shardchain_test.go
  internal/registry/registry.go
  node/node.go
  node/node_handler_test.go
  node/node_newblock_test.go
  node/node_test.go
Labels: WIP

#4516 Rotation fix and update.
  Makefile
  consensus/consensus_service.go
  consensus/consensus_service_test.go
  consensus/consensus_v2.go
  consensus/view_change.go
  core/blockchain.go
  core/blockchain_impl.go
  core/blockchain_leader_rotation.go
  core/blockchain_leader_rotation_test.go
  core/blockchain_stub.go
  core_test/shardchain_test.go
  crypto/bls/bls.go
  internal/params/config.go
  node/node_newblock.go
  test/build-localnet-validator.sh
Labels: Next Release

#4455 Mechanism for peers bloking.
  Makefile
  consensus/consensus_v2.go
  core/blockchain_impl.go
  internal/utils/blockedpeers/manager.go
  internal/utils/blockedpeers/manager_test.go
  internal/utils/lrucache/lrucache.go
  internal/utils/lrucache/lrucache_test.go
  node/node.go
  p2p/host.go
  p2p/security/security.go
  p2p/security/security_test.go
Labels: Next Release

#4359 Leader rotation. Check next leader aliveness.
  cmd/harmony/main.go
  consensus/consensus_v2.go
  consensus/quorum/quorum.go
  internal/utils/math.go
Labels: Next Release
